language: python
python:
  - "3.4"

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml"
  - "pip install -r ./travis/requirements.txt"

script:
  - "python ./travis/test_json.py"
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"
  
env:
  - PYTHONPATH=.

notifications:
  slack: kamranmackey:jGZfd7yguPMSjdorsZW0ZZER
  irc:
    channels:
      - "irc.esper.net#Ralybot"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} - %{build_url}"
  on_failure: always
  on_success: change
  skip_join: true
  
